# This is a basic workflow to help you get started with Actions

name: logging-system

on:
  workflow_dispatch:
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
        
      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash
        
        
